{
  "url": "https://api.github.com/repos/facebook/react/issues/13523",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/13523/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/13523/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/13523/events",
  "html_url": "https://github.com/facebook/react/issues/13523",
  "id": 355867792,
  "node_id": "MDU6SXNzdWUzNTU4Njc3OTI=",
  "number": 13523,
  "title": "Provide a way to throw error (maybe asynchronous) that can be handled by componentDidCatch",
  "user": {
    "login": "arch-mage",
    "id": 10350212,
    "node_id": "MDQ6VXNlcjEwMzUwMjEy",
    "avatar_url": "https://avatars3.githubusercontent.com/u/10350212?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/arch-mage",
    "html_url": "https://github.com/arch-mage",
    "followers_url": "https://api.github.com/users/arch-mage/followers",
    "following_url": "https://api.github.com/users/arch-mage/following{/other_user}",
    "gists_url": "https://api.github.com/users/arch-mage/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/arch-mage/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/arch-mage/subscriptions",
    "organizations_url": "https://api.github.com/users/arch-mage/orgs",
    "repos_url": "https://api.github.com/users/arch-mage/repos",
    "events_url": "https://api.github.com/users/arch-mage/events{/privacy}",
    "received_events_url": "https://api.github.com/users/arch-mage/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2018-08-31T07:21:41Z",
  "updated_at": "2019-06-18T14:18:02Z",
  "closed_at": "2018-09-11T17:20:06Z",
  "author_association": "NONE",
  "body": "**Do you want to request a *feature* or report a *bug*?**\r\nFeature request.\r\n\r\n**What is the current behavior?**\r\n`componentDidCatch` can only handle synchronous error.\r\n\r\n**What is the expected behavior?**\r\nThe capability of error boundaries to handle asynchronous error.\r\n\r\nThe error boundaries example in the docs is very similar with how an asynchronous error is handled in React.\r\n\r\n```javascript\r\nclass WithAsyncData extends React.Component {\r\n  constructor(props) {\r\n    super(props);\r\n    this.state = { error: null, value: null };\r\n  }\r\n\r\n  // using componentDidMount instead of componentDidCatch\r\n  componentDidMount() {\r\n    doAsynchronousThing()\r\n      .then(value => this.setState({ value }))\r\n      .catch(error => this.setState({ error }))\r\n  }\r\n\r\n  render() {\r\n    if (this.state.error) {\r\n      return <h1>An error occured.</h1>;\r\n    }\r\n    return this.props.children;\r\n  }\r\n}\r\n```\r\n\r\nUnfortunately, the new `componentDidCatch` lifecycle only aware of synchronous error. I think, it will be\r\ngood to provide a way to throw an error asynchronously, like:\r\n\r\n```javascript\r\nclass WithAsyncData extends React.Component {\r\n  constructor(props) {\r\n    super(props);\r\n    this.state = { error: null, value: null };\r\n  }\r\n\r\n  componentDidMount() {\r\n    doAsynchronousThing()\r\n      .then(value => this.setState({ value }))\r\n      .catch(error => this.throwError(error)) // throwing error asynchronously\r\n  }\r\n\r\n  render() {\r\n    if (this.state.error) {\r\n      return <h1>An error occured.</h1>;\r\n    }\r\n    return this.props.children;\r\n  }\r\n}\r\n```\r\n\r\nWith that, a network error can be handled in single place with a NetworkErrorBoundary component for example.",
  "closed_by": {
    "login": "arch-mage",
    "id": 10350212,
    "node_id": "MDQ6VXNlcjEwMzUwMjEy",
    "avatar_url": "https://avatars3.githubusercontent.com/u/10350212?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/arch-mage",
    "html_url": "https://github.com/arch-mage",
    "followers_url": "https://api.github.com/users/arch-mage/followers",
    "following_url": "https://api.github.com/users/arch-mage/following{/other_user}",
    "gists_url": "https://api.github.com/users/arch-mage/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/arch-mage/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/arch-mage/subscriptions",
    "organizations_url": "https://api.github.com/users/arch-mage/orgs",
    "repos_url": "https://api.github.com/users/arch-mage/repos",
    "events_url": "https://api.github.com/users/arch-mage/events{/privacy}",
    "received_events_url": "https://api.github.com/users/arch-mage/received_events",
    "type": "User",
    "site_admin": false
  }
}
