{
  "url": "https://api.github.com/repos/facebook/react/issues/14823",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/14823/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/14823/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/14823/events",
  "html_url": "https://github.com/facebook/react/issues/14823",
  "id": 408942139,
  "node_id": "MDU6SXNzdWU0MDg5NDIxMzk=",
  "number": 14823,
  "title": "Hook Error:  Hooks can only be called inside the body of a function component",
  "user": {
    "login": "rsokz",
    "id": 6425523,
    "node_id": "MDQ6VXNlcjY0MjU1MjM=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/6425523?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rsokz",
    "html_url": "https://github.com/rsokz",
    "followers_url": "https://api.github.com/users/rsokz/followers",
    "following_url": "https://api.github.com/users/rsokz/following{/other_user}",
    "gists_url": "https://api.github.com/users/rsokz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rsokz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rsokz/subscriptions",
    "organizations_url": "https://api.github.com/users/rsokz/orgs",
    "repos_url": "https://api.github.com/users/rsokz/repos",
    "events_url": "https://api.github.com/users/rsokz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rsokz/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 620368407,
      "node_id": "MDU6TGFiZWw2MjAzNjg0MDc=",
      "url": "https://api.github.com/repos/facebook/react/labels/Resolution:%20Needs%20More%20Information",
      "name": "Resolution: Needs More Information",
      "color": "fffde7",
      "default": false
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2019-02-11T19:36:13Z",
  "updated_at": "2019-02-12T18:53:37Z",
  "closed_at": "2019-02-12T18:25:05Z",
  "author_association": "NONE",
  "body": "<!--\r\n  Note: if the issue is about documentation or the website, please file it at:\r\n  https://github.com/reactjs/reactjs.org/issues/new\r\n-->\r\n\r\n**Do you want to request a *feature* or report a *bug*?**\r\nBug\r\n\r\n**What is the current behavior?**\r\nWhen using `useState()` hook in a functional component, I get the following error:\r\n\r\n> Hooks can only be called inside the body of a function component\r\n\r\n**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**\r\nThe functional component where the hook is being used:\r\n```\r\nconst AuthForm = () => {\r\n  const [value, setValue] = useState(1);\r\n\r\n  return (\r\n    <Paper square>\r\n      <Tabs\r\n        value={value}\r\n        indicatorColor=\"primary\"\r\n        textColor=\"primary\"\r\n        onChange={() => setValue(value)}\r\n      >\r\n        <Tab label=\"Active\" />\r\n        <Tab label=\"Active\" />\r\n      </Tabs>\r\n    </Paper>\r\n  );\r\n};\r\n```\r\npackage.json:\r\n```\r\n{\r\n  \"main\": \"index.js\",\r\n  \"scripts\": {\r\n    \"dev\": \"nodemon index.js --ignore client\"\r\n  },\r\n  \"dependencies\": {\r\n    \"@babel/core\": \"^7.0.0\",\r\n    \"@babel/preset-env\": \"^7.0.0\",\r\n    \"@babel/preset-react\": \"^7.0.0\",\r\n    \"@material-ui/core\": \"^3.9.2\",\r\n    \"apollo-boost\": \"^0.1.27\",\r\n    \"axios\": \"^0.18.0\",\r\n    \"babel-loader\": \"^8.0.5\",\r\n    \"bcrypt-nodejs\": \"0.0.3\",\r\n    \"body-parser\": \"^1.16.0\",\r\n    \"connect-mongo\": \"^2.0.3\",\r\n    \"express\": \"^4.16.4\",\r\n    \"express-graphql\": \"^0.7.1\",\r\n    \"express-session\": \"^1.15.6\",\r\n    \"graphql\": \"^14.1.1\",\r\n    \"html-webpack-plugin\": \"^3.2.0\",\r\n    \"lodash\": \"^4.17.4\",\r\n    \"mongoose\": \"^5.4.11\",\r\n    \"passport\": \"^0.4.0\",\r\n    \"passport-local\": \"^1.0.0\",\r\n    \"react\": \"16.8.1\",\r\n    \"react-apollo\": \"^2.4.1\",\r\n    \"react-dom\": \"16.8.1\",\r\n    \"react-router\": \"^4.3.1\",\r\n    \"react-router-dom\": \"^4.3.1\",\r\n    \"webpack\": \"^4.29.3\",\r\n    \"webpack-dev-middleware\": \"^3.5.2\"\r\n  },\r\n  \"devDependencies\": {\r\n    \"@babel/core\": \"^7.0.0\",\r\n    \"@babel/plugin-proposal-class-properties\": \"^7.3.0\",\r\n    \"@babel/plugin-transform-react-jsx\": \"^7.3.0\"\r\n  }\r\n}\r\n```\r\n\r\n**What is the expected behavior?**\r\nApp should run without any errors.\r\n\r\n**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**\r\nReact: 16.8.1\r\nReactDOM: 16.8.1\r\nChrome: 71.0.3578.98",
  "closed_by": {
    "login": "threepointone",
    "id": 18808,
    "node_id": "MDQ6VXNlcjE4ODA4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/18808?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/threepointone",
    "html_url": "https://github.com/threepointone",
    "followers_url": "https://api.github.com/users/threepointone/followers",
    "following_url": "https://api.github.com/users/threepointone/following{/other_user}",
    "gists_url": "https://api.github.com/users/threepointone/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/threepointone/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/threepointone/subscriptions",
    "organizations_url": "https://api.github.com/users/threepointone/orgs",
    "repos_url": "https://api.github.com/users/threepointone/repos",
    "events_url": "https://api.github.com/users/threepointone/events{/privacy}",
    "received_events_url": "https://api.github.com/users/threepointone/received_events",
    "type": "User",
    "site_admin": false
  }
}
