{
  "url": "https://api.github.com/repos/facebook/react/issues/15219",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/15219/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/15219/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/15219/events",
  "html_url": "https://github.com/facebook/react/issues/15219",
  "id": 425712868,
  "node_id": "MDU6SXNzdWU0MjU3MTI4Njg=",
  "number": 15219,
  "title": "Combination of componentDidCatch and hooks throws \"Should have a queue. This is likely a bug in React.\"",
  "user": {
    "login": "timkendrick",
    "id": 953720,
    "node_id": "MDQ6VXNlcjk1MzcyMA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/953720?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/timkendrick",
    "html_url": "https://github.com/timkendrick",
    "followers_url": "https://api.github.com/users/timkendrick/followers",
    "following_url": "https://api.github.com/users/timkendrick/following{/other_user}",
    "gists_url": "https://api.github.com/users/timkendrick/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/timkendrick/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/timkendrick/subscriptions",
    "organizations_url": "https://api.github.com/users/timkendrick/orgs",
    "repos_url": "https://api.github.com/users/timkendrick/repos",
    "events_url": "https://api.github.com/users/timkendrick/events{/privacy}",
    "received_events_url": "https://api.github.com/users/timkendrick/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 1109410193,
      "node_id": "MDU6TGFiZWwxMTA5NDEwMTkz",
      "url": "https://api.github.com/repos/facebook/react/labels/Component:%20Hooks",
      "name": "Component: Hooks",
      "color": "c2f27b",
      "default": false
    },
    {
      "id": 40929151,
      "node_id": "MDU6TGFiZWw0MDkyOTE1MQ==",
      "url": "https://api.github.com/repos/facebook/react/labels/Type:%20Bug",
      "name": "Type: Bug",
      "color": "b60205",
      "default": false
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 5,
  "created_at": "2019-03-27T00:53:53Z",
  "updated_at": "2019-07-03T12:38:32Z",
  "closed_at": null,
  "author_association": "NONE",
  "body": "**Do you want to request a *feature* or report a *bug*?**\r\n\r\nBug\r\n\r\n**What is the current behavior?**\r\n\r\nIf a component with hooks throws an error in its render function *after* the hooks have been defined, and that render error is caught via a `componentDidCatch` in a parent component, any subsequent components will have their hook order jumbled up on the next render.\r\n\r\nThis results in the app crashing with an **\"Uncaught Invariant Violation: Should have a queue. This is likely a bug in React. Please file an issue.\"** error (or different messages depending on the specific hooks used)\r\n\r\n**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**\r\n\r\nhttps://codesandbox.io/s/34mvmoln65\r\n\r\n(once loaded, open the dev tools console and click the 'Trigger re-render' button)\r\n\r\nRelevant source:\r\n\r\n```jsx\r\nfunction App(props) {\r\n  const [, setCounter] = React.useState(0);\r\n  return (\r\n    <div>\r\n      <ErrorHandler>\r\n        <ErrorThrower />\r\n      </ErrorHandler>\r\n      <StatefulComponent />\r\n      <button onClick={() => setCounter(value => value + 1)}>\r\n        Trigger re-render\r\n      </button>\r\n    </div>\r\n  );\r\n}\r\n\r\nfunction ErrorThrower() {\r\n  React.useMemo(() => undefined, []);\r\n  if (true) {\r\n    throw new Error(\"!!!\");\r\n  }\r\n  return <p>[Error component]</p>;\r\n}\r\n\r\nfunction StatefulComponent() {\r\n  React.useState(null);\r\n  return <p>[Stateful component]</p>;\r\n}\r\n\r\nclass ErrorHandler extends React.Component {\r\n  ...\r\n  componentDidCatch(error) {\r\n    ...\r\n  }\r\n}\r\n```\r\n\r\n**What is the expected behavior?**\r\n\r\nThe app should not crash, seeing as the `componentDidCatch()` ought to catch the render error and allow the rest of the app to render as normal\r\n\r\n**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**\r\n\r\nThis will presumably affect all versions of React that include the current Hooks implementation (v16.8 onwards)",
  "closed_by": null
}
