{
  "url": "https://api.github.com/repos/facebook/react/issues/15905",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/15905/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/15905/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/15905/events",
  "html_url": "https://github.com/facebook/react/issues/15905",
  "id": 456917923,
  "node_id": "MDU6SXNzdWU0NTY5MTc5MjM=",
  "number": 15905,
  "title": "Invariant Violation: Maximum update depth exceeded. with hooks",
  "user": {
    "login": "larspa",
    "id": 18027745,
    "node_id": "MDQ6VXNlcjE4MDI3NzQ1",
    "avatar_url": "https://avatars1.githubusercontent.com/u/18027745?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/larspa",
    "html_url": "https://github.com/larspa",
    "followers_url": "https://api.github.com/users/larspa/followers",
    "following_url": "https://api.github.com/users/larspa/following{/other_user}",
    "gists_url": "https://api.github.com/users/larspa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/larspa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/larspa/subscriptions",
    "organizations_url": "https://api.github.com/users/larspa/orgs",
    "repos_url": "https://api.github.com/users/larspa/repos",
    "events_url": "https://api.github.com/users/larspa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/larspa/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2019-06-17T12:52:22Z",
  "updated_at": "2019-09-03T11:44:28Z",
  "closed_at": "2019-09-03T11:44:27Z",
  "author_association": "NONE",
  "body": "Currently in React 16.8.6, we get this error when changing the state in a affected useEffect,\r\n```Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.```\r\n\r\nNow it can of course happen also in useEffects and it could be nice to have this message updated mention something about the \"dangerous\" combination of useStates and useEffects.",
  "closed_by": {
    "login": "threepointone",
    "id": 18808,
    "node_id": "MDQ6VXNlcjE4ODA4",
    "avatar_url": "https://avatars2.githubusercontent.com/u/18808?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/threepointone",
    "html_url": "https://github.com/threepointone",
    "followers_url": "https://api.github.com/users/threepointone/followers",
    "following_url": "https://api.github.com/users/threepointone/following{/other_user}",
    "gists_url": "https://api.github.com/users/threepointone/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/threepointone/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/threepointone/subscriptions",
    "organizations_url": "https://api.github.com/users/threepointone/orgs",
    "repos_url": "https://api.github.com/users/threepointone/repos",
    "events_url": "https://api.github.com/users/threepointone/events{/privacy}",
    "received_events_url": "https://api.github.com/users/threepointone/received_events",
    "type": "User",
    "site_admin": false
  }
}
