{
  "url": "https://api.github.com/repos/facebook/react/issues/16365",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/16365/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/16365/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/16365/events",
  "html_url": "https://github.com/facebook/react/issues/16365",
  "id": 479668806,
  "node_id": "MDU6SXNzdWU0Nzk2Njg4MDY=",
  "number": 16365,
  "title": "ErrorBoundary rendering multiple copies of itself when ref assignment fails",
  "user": {
    "login": "silverwind",
    "id": 115237,
    "node_id": "MDQ6VXNlcjExNTIzNw==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/115237?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/silverwind",
    "html_url": "https://github.com/silverwind",
    "followers_url": "https://api.github.com/users/silverwind/followers",
    "following_url": "https://api.github.com/users/silverwind/following{/other_user}",
    "gists_url": "https://api.github.com/users/silverwind/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/silverwind/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/silverwind/subscriptions",
    "organizations_url": "https://api.github.com/users/silverwind/orgs",
    "repos_url": "https://api.github.com/users/silverwind/repos",
    "events_url": "https://api.github.com/users/silverwind/events{/privacy}",
    "received_events_url": "https://api.github.com/users/silverwind/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 739761016,
      "node_id": "MDU6TGFiZWw3Mzk3NjEwMTY=",
      "url": "https://api.github.com/repos/facebook/react/labels/Component:%20Reconciler",
      "name": "Component: Reconciler",
      "color": "f9a798",
      "default": false
    },
    {
      "id": 40929151,
      "node_id": "MDU6TGFiZWw0MDkyOTE1MQ==",
      "url": "https://api.github.com/repos/facebook/react/labels/Type:%20Bug",
      "name": "Type: Bug",
      "color": "b60205",
      "default": false
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2019-08-12T14:12:35Z",
  "updated_at": "2019-10-07T15:29:01Z",
  "closed_at": null,
  "author_association": "NONE",
  "body": "**Do you want to request a *feature* or report a *bug*?**\r\n\r\nbug\r\n\r\n**What is the current behavior?**\r\n\r\nWhen a error occurs during the assignment of a `ref` (and maybe other conditions), a error boundary wrapping that error may get confused and it renders itself multiple times inside the same parent. See https://codesandbox.io/s/stoic-fermi-6etqb which renders:\r\n\r\n```html\r\n<div id=\"root\">\r\n  <div class=\"boundary\"><span>content</span></div>\r\n  <div class=\"boundary\"><span>error</span></div>\r\n</div>\r\n```\r\n\r\n**What is the expected behavior?**\r\n\r\n```html\r\n<div id=\"root\">\r\n  <div class=\"boundary\"><span>error</span></div>\r\n</div>\r\n```",
  "closed_by": null
}
