{
  "url": "https://api.github.com/repos/facebook/react/issues/3390",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/3390/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/3390/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/3390/events",
  "html_url": "https://github.com/facebook/react/issues/3390",
  "id": 60801270,
  "node_id": "MDU6SXNzdWU2MDgwMTI3MA==",
  "number": 3390,
  "title": "componentWillReceiveProps is called passing data from context",
  "user": {
    "login": "Tvaroh",
    "id": 8080251,
    "node_id": "MDQ6VXNlcjgwODAyNTE=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/8080251?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Tvaroh",
    "html_url": "https://github.com/Tvaroh",
    "followers_url": "https://api.github.com/users/Tvaroh/followers",
    "following_url": "https://api.github.com/users/Tvaroh/following{/other_user}",
    "gists_url": "https://api.github.com/users/Tvaroh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Tvaroh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Tvaroh/subscriptions",
    "organizations_url": "https://api.github.com/users/Tvaroh/orgs",
    "repos_url": "https://api.github.com/users/Tvaroh/repos",
    "events_url": "https://api.github.com/users/Tvaroh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Tvaroh/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2015-03-12T10:54:42Z",
  "updated_at": "2015-07-18T17:57:33Z",
  "closed_at": "2015-07-18T17:56:46Z",
  "author_association": "NONE",
  "body": "I'm getting very strange issue: `componentWillReceiveProps` is called on rendering when it shouldn't. The second argument (previous props) is okay and contain just one prop I have passed. But the first argument (new props) is in fact my React context. I was using `withContext` and tried to migrate on newer API (`getChildContext` with a wrapper) but the problem persisted.\n\nHow can it be? I don't change any prop and don't pass React context instead of props too.\n",
  "closed_by": {
    "login": "jimfb",
    "id": 9595985,
    "node_id": "MDQ6VXNlcjk1OTU5ODU=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/9595985?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jimfb",
    "html_url": "https://github.com/jimfb",
    "followers_url": "https://api.github.com/users/jimfb/followers",
    "following_url": "https://api.github.com/users/jimfb/following{/other_user}",
    "gists_url": "https://api.github.com/users/jimfb/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jimfb/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jimfb/subscriptions",
    "organizations_url": "https://api.github.com/users/jimfb/orgs",
    "repos_url": "https://api.github.com/users/jimfb/repos",
    "events_url": "https://api.github.com/users/jimfb/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jimfb/received_events",
    "type": "User",
    "site_admin": false
  }
}
