{
  "url": "https://api.github.com/repos/facebook/react/issues/4193",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/4193/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/4193/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/4193/events",
  "html_url": "https://github.com/facebook/react/issues/4193",
  "id": 90064019,
  "node_id": "MDU6SXNzdWU5MDA2NDAxOQ==",
  "number": 4193,
  "title": "Factory.type is deprecated. Access the class directly before passing it to createFactory",
  "user": {
    "login": "SystemParadox",
    "id": 1228777,
    "node_id": "MDQ6VXNlcjEyMjg3Nzc=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/1228777?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SystemParadox",
    "html_url": "https://github.com/SystemParadox",
    "followers_url": "https://api.github.com/users/SystemParadox/followers",
    "following_url": "https://api.github.com/users/SystemParadox/following{/other_user}",
    "gists_url": "https://api.github.com/users/SystemParadox/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SystemParadox/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SystemParadox/subscriptions",
    "organizations_url": "https://api.github.com/users/SystemParadox/orgs",
    "repos_url": "https://api.github.com/users/SystemParadox/repos",
    "events_url": "https://api.github.com/users/SystemParadox/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SystemParadox/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 6,
  "created_at": "2015-06-22T10:30:56Z",
  "updated_at": "2015-06-24T08:25:58Z",
  "closed_at": "2015-06-22T22:01:37Z",
  "author_association": "NONE",
  "body": "I am getting this warning but unable to work out why. I cannot find any documentation or other explanations for this error. What does it mean?\n\nWhat are the likely causes of this?\n\nThanks.\n",
  "closed_by": {
    "login": "sophiebits",
    "id": 6820,
    "node_id": "MDQ6VXNlcjY4MjA=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/6820?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sophiebits",
    "html_url": "https://github.com/sophiebits",
    "followers_url": "https://api.github.com/users/sophiebits/followers",
    "following_url": "https://api.github.com/users/sophiebits/following{/other_user}",
    "gists_url": "https://api.github.com/users/sophiebits/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sophiebits/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sophiebits/subscriptions",
    "organizations_url": "https://api.github.com/users/sophiebits/orgs",
    "repos_url": "https://api.github.com/users/sophiebits/repos",
    "events_url": "https://api.github.com/users/sophiebits/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sophiebits/received_events",
    "type": "User",
    "site_admin": false
  }
}
