{
  "url": "https://api.github.com/repos/facebook/react/issues/4199",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/4199/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/4199/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/4199/events",
  "html_url": "https://github.com/facebook/react/issues/4199",
  "id": 90489964,
  "node_id": "MDU6SXNzdWU5MDQ4OTk2NA==",
  "number": 4199,
  "title": "Component.render() is silently swallowing errors with no console output",
  "user": {
    "login": "xizhao",
    "id": 2066021,
    "node_id": "MDQ6VXNlcjIwNjYwMjE=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/2066021?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/xizhao",
    "html_url": "https://github.com/xizhao",
    "followers_url": "https://api.github.com/users/xizhao/followers",
    "following_url": "https://api.github.com/users/xizhao/following{/other_user}",
    "gists_url": "https://api.github.com/users/xizhao/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/xizhao/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/xizhao/subscriptions",
    "organizations_url": "https://api.github.com/users/xizhao/orgs",
    "repos_url": "https://api.github.com/users/xizhao/repos",
    "events_url": "https://api.github.com/users/xizhao/events{/privacy}",
    "received_events_url": "https://api.github.com/users/xizhao/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2015-06-23T21:03:36Z",
  "updated_at": "2016-11-08T07:15:51Z",
  "closed_at": "2015-06-23T21:17:07Z",
  "author_association": "NONE",
  "body": "A piece of code in my render function is error-ing.  A simple try/catch was able to capture and display the error, but without it React just silently proceeds by returning `null` in the render function and no error which makes it very difficult to find.  Basically if the error happens, render fails silently and displays an empty component.\n\nI am coming up with a JSFiddle to reprod in a simpler case for you to debug. \n",
  "closed_by": {
    "login": "sophiebits",
    "id": 6820,
    "node_id": "MDQ6VXNlcjY4MjA=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/6820?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sophiebits",
    "html_url": "https://github.com/sophiebits",
    "followers_url": "https://api.github.com/users/sophiebits/followers",
    "following_url": "https://api.github.com/users/sophiebits/following{/other_user}",
    "gists_url": "https://api.github.com/users/sophiebits/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sophiebits/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sophiebits/subscriptions",
    "organizations_url": "https://api.github.com/users/sophiebits/orgs",
    "repos_url": "https://api.github.com/users/sophiebits/repos",
    "events_url": "https://api.github.com/users/sophiebits/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sophiebits/received_events",
    "type": "User",
    "site_admin": false
  }
}
