{
  "url": "https://api.github.com/repos/facebook/react/issues/4957",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/4957/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/4957/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/4957/events",
  "html_url": "https://github.com/facebook/react/issues/4957",
  "id": 108077172,
  "node_id": "MDU6SXNzdWUxMDgwNzcxNzI=",
  "number": 4957,
  "title": "Invariant Violation: Only a ReactOwner can have refs",
  "user": {
    "login": "seekshiva",
    "id": 484349,
    "node_id": "MDQ6VXNlcjQ4NDM0OQ==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/484349?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/seekshiva",
    "html_url": "https://github.com/seekshiva",
    "followers_url": "https://api.github.com/users/seekshiva/followers",
    "following_url": "https://api.github.com/users/seekshiva/following{/other_user}",
    "gists_url": "https://api.github.com/users/seekshiva/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/seekshiva/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/seekshiva/subscriptions",
    "organizations_url": "https://api.github.com/users/seekshiva/orgs",
    "repos_url": "https://api.github.com/users/seekshiva/repos",
    "events_url": "https://api.github.com/users/seekshiva/events{/privacy}",
    "received_events_url": "https://api.github.com/users/seekshiva/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 13,
  "created_at": "2015-09-24T07:48:31Z",
  "updated_at": "2016-07-06T11:40:05Z",
  "closed_at": "2015-09-24T17:59:59Z",
  "author_association": "NONE",
  "body": "I get this error whenever I try to use any plugin.\n\nReferences: yuanyan/boron#11, casesandberg/react-bounds#4.\n\nSince others aren't complaining about this issue in those repos, I'm bound to think it might be something with my setup.\n\nCan someone help me resolve this issue?\n",
  "closed_by": {
    "login": "seekshiva",
    "id": 484349,
    "node_id": "MDQ6VXNlcjQ4NDM0OQ==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/484349?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/seekshiva",
    "html_url": "https://github.com/seekshiva",
    "followers_url": "https://api.github.com/users/seekshiva/followers",
    "following_url": "https://api.github.com/users/seekshiva/following{/other_user}",
    "gists_url": "https://api.github.com/users/seekshiva/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/seekshiva/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/seekshiva/subscriptions",
    "organizations_url": "https://api.github.com/users/seekshiva/orgs",
    "repos_url": "https://api.github.com/users/seekshiva/repos",
    "events_url": "https://api.github.com/users/seekshiva/events{/privacy}",
    "received_events_url": "https://api.github.com/users/seekshiva/received_events",
    "type": "User",
    "site_admin": false
  }
}
