{
  "url": "https://api.github.com/repos/facebook/react/issues/9253",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/9253/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/9253/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/9253/events",
  "html_url": "https://github.com/facebook/react/issues/9253",
  "id": 216869490,
  "node_id": "MDU6SXNzdWUyMTY4Njk0OTA=",
  "number": 9253,
  "title": "unstable_handleError only seems to work on initial render",
  "user": {
    "login": "oveddan",
    "id": 891755,
    "node_id": "MDQ6VXNlcjg5MTc1NQ==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/891755?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oveddan",
    "html_url": "https://github.com/oveddan",
    "followers_url": "https://api.github.com/users/oveddan/followers",
    "following_url": "https://api.github.com/users/oveddan/following{/other_user}",
    "gists_url": "https://api.github.com/users/oveddan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oveddan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oveddan/subscriptions",
    "organizations_url": "https://api.github.com/users/oveddan/orgs",
    "repos_url": "https://api.github.com/users/oveddan/repos",
    "events_url": "https://api.github.com/users/oveddan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oveddan/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2017-03-24T18:27:40Z",
  "updated_at": "2019-05-27T06:56:40Z",
  "closed_at": "2017-03-24T19:27:56Z",
  "author_association": "NONE",
  "body": "With a component that has the error boundary `unstable_handleError` in it, `unstable_handleError` only seems to be invoked if an error occurs on the initial render, not on subsequent renders.  \r\n\r\nFor example, in the following code, visible at (https://codepen.io/stangogh/pen/ZeRVwR), when the `TriggerError` component is rendered initially, it recovers and renders the `Error` component:\r\n\r\n```javascript\r\nconst TriggerError = () => { return 5 / b }\r\n\r\nclass InnerContainer extends React.Component {\r\n  constructor(props) {\r\n    super(props)\r\n    \r\n    this.state = {}\r\n  }\r\n  \r\n  unstable_handleError(e) {\r\n    console.log(\"unstable_handleError\")\r\n    console.log(\"continuing\")\r\n    \r\n    this.setState({error: true})\r\n  }\r\n  \r\n  render() {\r\n    if (this.state.error) {\r\n      return <div>Error!</div>\r\n    }\r\n    \r\n    return <TriggerError />\r\n    \r\n    return <h1>Hello world</h1>\r\n  }\r\n}\r\n\r\nReactDOM.render(\r\n  React.createElement(InnerContainer),\r\n  document.getElementById('root')\r\n)\r\n```\r\n\r\nHowever, if the TriggerError component is rendered after a delay, unstable_handleError never gets invoked and the component never recovers (https://codepen.io/stangogh/pen/RpJYqP):\r\n\r\n```javascript\r\nconst TriggerError = () => { return 5 / b }\r\n\r\nclass InnerContainer extends React.Component {\r\n  constructor(props) {\r\n    super(props)\r\n    \r\n    this.state = {}\r\n  }\r\n  \r\n  componentWillMount() {\r\n    setTimeout(() => {\r\n      this.setState({triggerError: true})\r\n    }, 1000)\r\n  }\r\n  \r\n  unstable_handleError(e) {\r\n    console.log(\"unstable_handleError\")\r\n    console.log(\"continuing\")\r\n    \r\n    this.setState({error: true})\r\n  }\r\n  \r\n  render() {\r\n    if (this.state.error) {\r\n      return <div>Error!</div>\r\n    }\r\n    \r\n    if (this.state.triggerError) {\r\n      return <TriggerError />\r\n    }\r\n    \r\n    return <h1>Hello world</h1>\r\n  }\r\n}\r\n\r\nReactDOM.render(\r\n  React.createElement(InnerContainer),\r\n  document.getElementById('root')\r\n)\r\n```\r\n",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
